import {HelperCulture} from "@Main/helper/Helper.Culture";
import {HelperDOM} from "@Main/helper/Helper.DOM";
import {HelperObject} from "@Main/helper/Helper.Object";
import {HelperUrl} from "@Main/helper/Helper.Url";
import {HelperUser} from "@Main/helper/Helper.User";
import {HelperString} from "@Main/helper/Helper.String";
import {HelperLookup} from "@Main/helper/Helper.Lookup";
import {HelperPosting } from "@Main/helper/Helper.Posting";
import {HelperConfirm} from "@Main/helper/Helper.Confirm";
import {HelperBatch} from "@Main/helper/Helper.Batch";
import {HelperVisibility} from "@Main/helper/Helper.Visibility";
import {HelperDatabase} from "@Main/helper/Helper.Database";
import {HelperDate} from "@Main/helper/Helper.Date";
import {HelperDistinct} from "@Main/helper/Helper.Distinct";
import {HelperNumber} from "@Main/helper/Helper.Number";
import {HelperMap} from "@Main/helper/Helper.Map";
import {helperBase as Helper, mergeDeep} from "../Content/ts/helper/helper";
import {HelperImage} from "@Main/helper/Helper.Image";
import {HelperBarcode} from "../Content/ts/helper/Helper.Barcode";
import {HelperDownload} from "@Main/helper/Helper.Download";
window.Helper = mergeDeep(window.Helper, Helper);
window.Helper.Batch ||= HelperBatch;
window.Helper.Confirm ||= HelperConfirm;
window.Helper.Culture ||= HelperCulture;
window.Helper.Database ||= HelperDatabase;
window.Helper.Date ||= HelperDate;
window.Helper.Distinct ||= HelperDistinct;
window.Helper.DOM ||= HelperDOM;
window.Helper.Image ||= HelperImage;
window.Helper.Lookup ||= HelperLookup;
window.Helper.Map ||= HelperMap;
window.Helper.Number ||= HelperNumber;
window.Helper.Object ||= HelperObject;
window.Helper.Posting ||= HelperPosting;
window.Helper.String ||= HelperString;
window.Helper.Url ||= HelperUrl;
window.Helper.User ||= HelperUser;
window.Helper.Visibility ||= HelperVisibility;
window.Helper.Barcode ||= HelperBarcode;
window.Helper.Download ||= HelperDownload;
