const generateJsTask = require("../../../gulp-core/gulptaskCore").generateJsTask;

module.exports = function() {
    // Original location : .\
    let jsFiles = [
        "content/js/system/jakecache.js",
        "../../node_modules/jquery/dist/jquery.js",
        "../../node_modules/jquery-ui-dist/jquery-ui.js",
		"../../node_modules/hammerjs/hammer.js",
        "../../node_modules/jquery-hammerjs/jquery.hammer.js",
        "../../node_modules/bootstrap/dist/js/bootstrap.js",
        "../../node_modules/knockout/build/output/knockout-latest.debug.js",
        "../../node_modules/knockout-punches/knockout.punches.js",
        "../../node_modules/knockout.validation/dist/knockout.validation.js",
        "Content/js/system/knockout.wrap.js",
        "../../node_modules/yarn-mprogress/build/js/mprogress.js",
        "../../node_modules/sammy/lib/sammy.js",
        "../../node_modules/jquery.flot/jquery.flot.js",
        "../../node_modules/flot-axislabels/jquery.flot.axislabels.js",
        "../../node_modules/jquery.flot/jquery.flot.resize.js",
        "../../node_modules/moment/moment.js",
        "../../node_modules/jquery.flot/jquery.flot.stack.js",
        "../../node_modules/moment-duration-format/lib/moment-duration-format.js",
        "../../node_modules/moment-timezone/builds/moment-timezone-with-data-10-year-range.js",
        "../../node_modules/fullcalendar/dist/fullcalendar.js",
        "../../node_modules/nouislider/distribute/jquery.nouislider.all.js",
        "../../node_modules/fullcalendar/dist/lang-all.js",
        "Content/js/system/jquery.mCustomScrollbar.concat.min.js",
        "../../node_modules/node-waves/dist/waves.js",
        "../../node_modules/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.js",
        "Content/js/system/bootstrap-growl.js",
        "../../node_modules/bootstrap-select/dist/js/bootstrap-select.js",
        "../../node_modules/autosize/dist/autosize.js",
		"Content/js/material/functions.js",
		"../../node_modules/log4javascript/log4javascript.js",
        "../../node_modules/@microsoft/signalr/dist/browser/signalr.js",
        "../../node_modules/async/lib/async.js",
        "../../node_modules/cldrjs/dist/cldr.js",
        "../../node_modules/cldrjs/dist/cldr/unresolved.js",
        "../../node_modules/cldrjs/dist/cldr/event.js",
        "../../node_modules/cldrjs/dist/cldr/supplemental.js",
        "../../node_modules/globalize/dist/globalize.js",
        "../../node_modules/globalize/dist/globalize/message.js",
        "../../node_modules/globalize/dist/globalize/number.js",
        "../../node_modules/globalize/dist/globalize/plural.js",
        "../../node_modules/globalize/dist/globalize/date.js",
        "../../node_modules/globalize/dist/globalize/currency.js",
        "../../node_modules/globalize/dist/globalize/relative-time.js",
        "content/js/system/fileinput.js",
        "content/js/system/sweet-alert.js",
        "../../node_modules/eonasdan-bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js",
        "../../node_modules/leaflet/dist/leaflet-src.js",
        "content/js/system/leaflet.bouncemarker-1.0.0.js",
        "../../node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js",
        "Content/js/system/jquery.signaturepad.min.js",
        "Content/js/mfb/modernizr.touch.js",
        "Content/js/ics/ics.deps.min.js",
        "Content/js/ics/ics.min.js",
        "../../node_modules/select2/dist/js/select2.full.js",
        "../../node_modules/lodash/lodash.js",
        "../../node_modules/webrtc-adapter/out/adapter.js",
        "../../node_modules/url-search-params-polyfill/index.js",
		"../../node_modules/qrcode/build/qrcode.js",
		"../../node_modules/knockout-sortable/build/knockout-sortable.js",
		"../../node_modules/dropzone/dist/dropzone.js",
		"../../node_modules/polyline-encoded/Polyline.encoded.js"
    ];

    generateJsTask(__filename, jsFiles);

};
