import "../Content/ts/Extensions.Promise"
import "../Content/ts/Log"
import "../Content/ts/TemplateReport"
import "../Content/ts/namespace";
import "../Content/ts/knockout.validation.custom";
import "../Content/ts/knockout.custom";
import "../Content/ts/knockout.custom.datePicker";
import "../Content/ts/knockout.custom.dateText";
import "../Content/ts/knockout.custom.durationText";
import "../Content/js/system/knockout.wrap.js";
import "../Content/ts/knockout.custom.lookupValue";
import "../Content/ts/knockout.custom.money";
import "../Content/ts/knockout.custom.signaturePad";
import "../Content/ts/knockout.custom.translatedText";
import "./mainHelperTs";
import "../Content/ts/helper/Helper.Database";
import "../Content/ts/AuthorizationManager";
import "../Content/ts/DefaultViewModel";
import "../Content/ts/ViewModelBase";
import "../Content/ts/OfflineBootstrapper";
import "../Content/ts/Crm.Token";
import "../Content/ts/knockout.component.barcode";
