import "../Content/ts/ArticleDetailsTeamsTabViewModel";
import "../Content/ts/ArticleUserGroupRelationshipEditModalViewModel";
import "../Content/ts/DispatchDetailsViewModelExtension"
import "../Content/ts/DispatchScheduleModalViewModelExtension"
import "../Content/ts/Helper.Article.Extension"
import "../Content/ts/Helper.User.Extension"
import "../Content/ts/OfflineModel";
import "../Content/ts/OverlappingArticleUserGroupRelationshipValidator";
import "../Content/ts/ServiceOrderDispatchListIndexViewModelExtension"
import "../Content/ts/ServiceOrderDetailsDispatchesTabViewModelExtension"
import "../Content/ts/ServiceOrderTimePostingEditModalViewModelExtension"
import "../Content/ts/ServiceTeamListIndexViewModel";
import "../Content/ts/UserDetailsViewModelExtension";
import "../Content/ts/UserGroupDetailsArticlesTabViewModel";
import "../Content/ts/UserGroupDetailsDispatchesTabViewModel";
import "../Content/ts/UserGroupDetailsViewModelExtension";
import "../Content/ts/UserGroupCreateViewModelExtension";
import "../Content/ts/UserGroupListIndexViewModelExtension";
import "../Content/ts/validation-rules";
