import "../Content/ts/NoteDisplayTextProvider";
import "../Content/ts/ServiceOrderCreateViewModel";
import "../Content/ts/DispatchAdHocViewModel";
import "../Content/ts/DispatchAppointmentModalViewModel";
import "../Content/ts/DispatchChangeStatusModalViewModel";
import "../Content/ts/DispatchCancelModalViewModel";
import "../Content/ts/DispatchDetailsViewModel";
import "../Content/ts/DispatchDetailsInstallationsTabViewModel";
import "../Content/ts/ServiceOrderDetailsJobsTabViewModel";
import "../Content/ts/DispatchDetailsJobsTabViewModel";
import "../Content/ts/ServiceOrderDetailsMaterialsTabViewModel";
import "../Content/ts/DispatchDetailsMaterialsTabViewModel";
import "../Content/ts/ServiceOrderReportViewModel";
import "../Content/ts/DispatchReportViewModel";
import "../Content/ts/DispatchReportPreviewModalViewModel";
import "../Content/ts/ServiceOrderDetailsTimePostingsTabViewModel";
import "../Content/ts/ServiceOrderDetailsExpensePostingsTabViewModel";
import "../Content/ts/ServiceOrderDetailsErrorTabViewModel";
import "../Content/ts/DispatchDetailsTimePostingsTabViewModel";
import "../Content/ts/DispatchDetailsExpensePostingsTabViewModel";
import "../Content/ts/DispatchDetailsErrorTabViewModel";
import "../Content/ts/DispatchDocumentAttributeEditModalViewModel";
import "../Content/ts/DispatchRejectModalViewModel";
import "../Content/ts/DispatchReportRecipientsModalViewModel";
import "../Content/ts/DispatchScheduleModalViewModel";
import "../Content/ts/DispatchSignatureEditModalViewModel";
import "../Content/ts/helper/Helper.Contact.Extension";
import "../Content/ts/helper/Helper.Dispatch";
import "../Content/ts/helper/Helper.ReplenishmentOrder";
import "../Content/ts/helper/Helper.Installation";
import "../Content/ts/helper/Helper.Service";
import "../Content/ts/helper/Helper.ServiceContract";
import "../Content/ts/helper/Helper.ServiceCase";
import "../Content/ts/helper/Helper.ServiceCaseTemplate";
import "../Content/ts/helper/Helper.ServiceObject";
import "../Content/ts/helper/Helper.ServiceOrder";
import "../Content/ts/helper/Helper.ServiceOrder.createServiceOrderData";
import "../Content/ts/helper/Helper.ServiceOrderTime";
import "../Content/ts/helper/Helper.ServiceOrderTimePosting";
import "../Content/ts/helper/Helper.InstallationPosition";
import "../Content/ts/helper/Helper.PerDiem.Extension";
import "../Content/ts/InstallationAddressRelationshipEditModalViewModel";
import "../Content/ts/InstallationCreateViewModel";
import "../Content/ts/InstallationPositionListIndexViewModel";
import "../Content/ts/InstallationDetailsDocumentsTabViewModel";
import "../Content/ts/InstallationDetailsPositionsTabViewModel";
import "../Content/ts/InstallationDetailsRelationshipsTabViewModel";
import "../Content/ts/InstallationDetailsViewModel";
import "../Content/ts/InstallationDocumentAttributeEditModalViewModel";
import "../Content/ts/InstallationListIndexViewModel";
import "../Content/ts/InstallationPositionEditModalViewModel";
import "../Content/ts/knockout.component.serviceCaseDashboardList"
import "../Content/ts/knockout.component.statisticsKeyInfo"
import "../Content/ts/knockout.component.todaysDispatches";
import "../Content/ts/MaintenancePlanEditModalViewModel";
import "../Content/ts/OfflineModel";
import "../Content/ts/OverlappingTimeEntryValidator";
import "../Content/ts/HelperTimeEntryExtension";
import "../Content/ts/TimeEntryCloseModalViewModelExtension";
import "../Content/ts/TimeEntryIndexViewModelExtension";
import "../Content/ts/PerDiemReportDetailsModalViewModelExtension";
import "../Content/ts/PersonCreateViewModelExtension";
import "../Content/ts/PersonDetailsStaffTabViewModelExtensions";
import "../Content/ts/PersonDetailsViewModelExtensions";
import "../Content/ts/PersonExtensions";
import "../Content/ts/ReplenishmentOrderItemEditModalViewModel";
import "../Content/ts/ReplenishmentOrderItemListIndexViewModel";
import "../Content/ts/ReplenishmentOrderReportViewModel";
import "../Content/ts/ServiceContractAddressRelationshipEditModalViewModel";
import "../Content/ts/ServiceContractCreateViewModel";
import "../Content/ts/ServiceContractDetailsDocumentsTabViewModel";
import "../Content/ts/ServiceContractDetailsInstallationsTabViewModel";
import "../Content/ts/ServiceContractDetailsMaintenancePlansTabViewModel";
import "../Content/ts/ServiceContractDetailsRelationshipsTabViewModel";
import "../Content/ts/ServiceContractDetailsViewModel";
import "../Content/ts/ServiceContractDocumentAttributeEditModalViewModel";
import "../Content/ts/ServiceContractInstallationRelationshipEditModalViewModel";
import "../Content/ts/ServiceContractListIndexViewModel";
import "../Content/ts/ServiceCaseAddToServiceOrderModalViewModel";
import "../Content/ts/ServiceCaseCreateServiceOrderModalViewModel";
import "../Content/ts/ServiceCaseCreateViewModel";
import "../Content/ts/ServiceCaseDetailsViewModel";
import "../Content/ts/ServiceCaseDetailsDocumentsTabViewModel";
import "../Content/ts/ServiceCaseDetailsErrorTabViewModel";
import "../Content/ts/ServiceCaseDocumentAttributeEditModalViewModel";
import "../Content/ts/ServiceCaseListIndexViewModel";
import "../Content/ts/InstallationDetailsServiceCasesTabViewModel";
import "../Content/ts/ServiceCaseSetStatusModalViewModel";
import "../Content/ts/ServiceCaseTemplateCreateViewModel";
import "../Content/ts/ServiceCaseTemplateDetailsViewModel";
import "../Content/ts/ServiceCaseTemplateListIndexViewModel";
import "../Content/ts/ServiceObjectAddInstallationModalViewModel";
import "../Content/ts/ServiceObjectCreateViewModel";
import "../Content/ts/ServiceObjectDetailsViewModel";
import "../Content/ts/ServiceObjectDetailsInstallationsTabViewModel";
import "../Content/ts/ServiceObjectDetailsPersonsTabViewModel";
import "../Content/ts/ServiceObjectListIndexViewModel";
import "../Content/ts/ServiceOrderDispatchListIndexViewModel";
import "../Content/ts/DashboardCalendarWidgetViewModelExtension";
import "../Content/ts/ServiceOrderHeadListIndexViewModel";
import "../Content/ts/InstallationDetailsServiceOrdersTabViewModel";
import "../Content/ts/ServiceOrderCreateInvoiceModalViewModel";
import "../Content/ts/ServiceOrderCloseModalViewModel";
import "../Content/ts/ServiceOrderDetailsServiceCasesTabViewModel";
import "../Content/ts/DispatchDetailsServiceCasesTabViewModel";
import "../Content/ts/ServiceOrderDetailsViewModel";
import "../Content/ts/ServiceOrderDetailsDispatchesTabViewModel";
import "../Content/ts/ServiceOrderDetailsInstallationsTabViewModel";
import "../Content/ts/ServiceOrderDetailsDocumentsTabViewModel";
import "../Content/ts/DispatchDetailsDocumentsTabViewModel";
import "../Content/ts/ServiceOrderMaterialEditModalViewModel";
import "../Content/ts/ServiceOrderMaterialReportScheduledMaterialModalViewModel";
import "../Content/ts/ServiceOrderTemplateCreateViewModel";
import "../Content/ts/ServiceOrderTemplateDetailsViewModel";
import "../Content/ts/ServiceOrderTemplateDetailsDocumentsTabViewModel";
import "../Content/ts/ServiceOrderTemplateDetailsJobsTabViewModel";
import "../Content/ts/ServiceOrderTemplateDetailsMaterialsTabViewModel";
import "../Content/ts/ServiceOrderTemplateDetailsTimePostingsTabViewModel";
import "../Content/ts/ServiceOrderTemplateListIndexViewModel";
import "../Content/ts/ServiceOrderTimeEditModalViewModel";
import "../Content/ts/ServiceOrderTimePostingEditModalViewModel";
import "../Content/ts/ServiceOrderTimePostingDispatchRelinkModalViewModel.ts"
import "../Content/ts/ServiceOrderExpensePostingEditModalViewModel";
import "../Content/ts/ServiceOrderErrorTypeEditModalViewModel";
import "../Content/ts/ServiceOrderErrorCauseEditModalViewModel";
import "../Content/ts/CompanyDetailsInstallationsTabViewModel";
import "../Content/ts/CompanyDetailsServiceCasesTabViewModel";
import "../Content/ts/CompanyDetailsServiceContractsTabViewModel";
import "../Content/ts/CompanyDetailsServiceOrdersTabViewModel";
import "../Content/ts/ServiceContractDetailsServiceOrdersTabViewModel";
import "../Content/ts/StatisticsKeyEditModalViewModel";
import "../Content/ts/StatisticsKeyInfoViewModel";
import "../Content/ts/validation-rules";
import "../Content/ts/NoteExtensions";
import "../Content/ts/jaydata.custom.functions";
import "../Content/ts/knockout.custom.tabBreadcrumb";
import "../Content/ts/knockout.custom.fromToDates";
import "../Content/ts/ArticleDetailsViewModelExtension";
import "../Content/ts/TopSearchViewModelExtension";
import "../Content/ts/UserDetailsViewModelExtension";
import "../Content/ts/AccountUserProfileViewModelExtension";
import "../Content/ts/ServiceOrderDetailsNotesTabViewModel";
import "../Content/ts/CompanyDetailsRelationshipsTabViewModelExtension"
import "../Content/ts/DispatchDetailsNotesTabViewModel";
import "../Content/ts/DispatchDetailsRelatedOrdersTabViewModel";
import "../Content/ts/InstallationCompanyRelationshipEditModalViewModel"
import "../Content/ts/InstallationDetailsRelationshipsTabViewModel"
import "../Content/ts/InstallationPersonRelationshipEditModalViewModel"
import "../Content/ts/InstallationDetailsNotesTabViewModel";
import "../Content/ts/LookupEditModalViewModelExtension";
import "../Content/ts/PersonDetailsRelationshipsTabViewModelExtension"
import "../Content/ts/ServiceCaseDetailsNotesTabViewModel";
import "../Content/ts/ServiceOrderNoInvoiceModalViewModel";
import "../Content/ts/ServiceContractDetailsNotesTabViewModel";
import "../Content/ts/ServiceObjectDetailsNotesTabViewModel";
import "../Content/ts/ServiceOrderTemplateDetailsNotesTabViewModel";
import "../Content/ts/UserDetailsAddSkillModalViewModel";
import "../Content/ts/ServiceCaseDetailsInstallationTabViewModel";
import "../Content/ts/ServiceCaseAddContactModalViewModel"
import "../Content/ts/ServiceCaseDetailsServiceOrdersTabViewModel";
import "../Content/ts/ArticleDetailsInstallationsTabViewModel";
import "../Content/ts/ArticleDetailsRelationshipsTabViewModelExtension";
import "../Content/ts/ServiceObjectDetailsServiceOrdersTabViewModel";
import "../Content/ts/ServiceObjectDetailsServiceContractsTabViewModel";
import "../Content/ts/ServiceObjectDetailsServiceCasesTabViewModel";
import {HelperDispatch} from "@Crm.Service/helper/Helper.Dispatch";
import {HelperInstallation} from "@Crm.Service/helper/Helper.Installation";
import {HelperInstallationPosition} from "@Crm.Service/helper/Helper.InstallationPosition";
import {HelperReplenishmentOrder} from "@Crm.Service/helper/Helper.ReplenishmentOrder";
import {HelperService} from "@Crm.Service/helper/Helper.Service";
import {HelperServiceCase} from "@Crm.Service/helper/Helper.ServiceCase";
import {HelperServiceCaseTemplate} from "@Crm.Service/helper/Helper.ServiceCaseTemplate";
import {HelperServiceContract} from "@Crm.Service/helper/Helper.ServiceContract";
import {HelperServiceObject} from "@Crm.Service/helper/Helper.ServiceObject";
import {HelperServiceOrder} from "@Crm.Service/helper/Helper.ServiceOrder";
import {HelperServiceOrderMaterial} from "@Crm.Service/helper/Helper.ServiceOrderMaterial";
import {HelperServiceOrderTime} from "@Crm.Service/helper/Helper.ServiceOrderTime";
import {HelperServiceOrderTimePosting} from "@Crm.Service/helper/Helper.ServiceOrderTimePosting";
import {HelperStatisticsKey} from "@Crm.Service/helper/Helper.StatisticsKey";

window.Helper.Dispatch ||= HelperDispatch;
window.Helper.Installation ||= HelperInstallation;
window.Helper.InstallationPosition ||= HelperInstallationPosition;
window.Helper.ReplenishmentOrder ||= HelperReplenishmentOrder;
window.Helper.Service ||= HelperService;
window.Helper.ServiceCase ||= HelperServiceCase;
window.Helper.ServiceCaseTemplate ||= HelperServiceCaseTemplate;
window.Helper.ServiceContract ||= HelperServiceContract;
window.Helper.ServiceObject ||= HelperServiceObject;
window.Helper.ServiceOrder ||= HelperServiceOrder;
window.Helper.ServiceOrderTime ||= HelperServiceOrderTime;
window.Helper.ServiceOrderTimePosting ||= HelperServiceOrderTimePosting;
window.Helper.StatisticsKey ||= HelperStatisticsKey;
window.Helper.ServiceOrderMaterial ||= HelperServiceOrderMaterial;